version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      build:
        patterns:
          - 'autoprefixer'

      lint:
        patterns:
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'

      logging:
        patterns:
          - '*-pino'
          - '*-pino-format'
          - 'pino'
          - 'pino-*'

      tools:
        patterns:
          - 'husky'
          - 'jest'
          - 'nodemon'
          - 'npm-run-all'

      types:
        patterns:
          - '@types/*'

    ignore:
      - dependency-name: 'eslint-*'
      - dependency-name: 'eslint'

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
